import React from 'react'
import style from './styles/Loader.module.css'

const Loader = () => {
  return (
    <section className={style.loaderContainer}>
      <div className={style.ldsDualRing}>

      </div>
    </section>
  )
}

export default Loader






/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */
/* FAZER PODER VER AS COSTAS DO POKEMON */